/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    inner class Hihi{
        // this will hit "my custom rule"
    }
}

fun main() {
    println(App().greeting)
}
